name: BinarySearch

on:
  push:
    branches: [ "master" ]
    paths-ignore:
     - ".github/workflows/**"
     - "**.txt"
  pull_request:
    branches: [ "master" ]
    paths-ignore:
     - ".github/workflows/**"
     - "**.txt"

  workflow_dispatch:

jobs:
  linux_build:
    name: test, build and upload in telegram
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run test
        run: |
          python test_binary_search.py
          
      - name: Build executable
        run: pyinstaller --name=${{ github.job }} --onefile app.py -p binary_search.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary_search
          path: dist/
          
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Workflow triggered by ${{ github.event_name }} event
          document: dist/${{ github.job }}


  windows_build:
     name: test, build and upload
     runs-on: windows-latest

     steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: "3.x"

        - name: Install dependecies
          run: |
            py -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: |
            py test_binary_search.py

        - name: Build executable
          run: pyinstaller --name=${{ github.job }} --onefile app.py -p binary_search.py

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: binary_search
            path: dist\


  send_windows_build:
     needs: windows_build
     runs-on: linux-latest

     steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: binary_search

        - name: Send Telegram message
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: Workflow triggered by ${{ github.event_name }} event
            document: dist/binary_search

  docker_build:
      name: containerisation
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Login in docker
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - uses: docker/setup-buildx-action@v2

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/binary_search_app:latest
    
  codacy_check:
      name: static code review
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - uses: codacy/codacy-analysis-cli-action@master
             
  auto_formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install black

      - name: Format code
        run: black .

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Auto-format Python code [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
